# Generated by Django 3.2.8 on 2021-10-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
