# Generated by Django 3.2.8 on 2021-10-27 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_request', models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=10, null=True)),
                ('received_request', models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=10, null=True)),
                ('connection_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, to='users.Connection'),
        ),
    ]
