# Generated by Django 3.2.9 on 2021-12-22 19:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FlagInappropriate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FourthLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Question/Errors', 'Question/Errors'), ('Discussion and Informative', 'Discussion and Informative'), ('Skeleton Code', 'Skeleton Code')], max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('skeleton_code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby')], max_length=100)),
                ('scope_of_work', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecondLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SkeletonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('skeleton_code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby')], max_length=100)),
                ('scope_of_work', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThirdLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.firstlevelcategory')),
                ('second_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstCatThird', to='post.secondlevelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SkeletonPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post.skeletonpost')),
            ],
        ),
    ]
