# Generated by Django 3.2.9 on 2021-12-16 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlagInappropriate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Question/Errors', 'Question/Errors'), ('Discussion and Informative', 'Discussion and Informative'), ('Skeleton Code', 'Skeleton Code')], max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('skeleton_code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], max_length=100)),
                ('scope_of_work', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkeletonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='skeleton_image/')),
                ('skeleton_code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], max_length=100)),
                ('scope_of_work', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
