# Generated by Django 3.2.9 on 2021-12-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211218_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthlevelcategory',
            name='first_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.firstlevelcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourthlevelcategory',
            name='second_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.secondlevelcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourthlevelcategory',
            name='third_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.thirdlevelcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondlevelcategory',
            name='first_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.firstlevelcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thirdlevelcategory',
            name='first_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.firstlevelcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thirdlevelcategory',
            name='second_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.secondlevelcategory'),
            preserve_default=False,
        ),
    ]
