# Generated by Django 3.2.9 on 2021-12-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211218_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='fourthlevelcategory',
            name='third_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstCatFourth', to='post.thirdlevelcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='scope_of_work',
            field=models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='secondlevelcategory',
            name='first_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstCat', to='post.firstlevelcategory'),
        ),
        migrations.AlterField(
            model_name='skeletonpost',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skeletonpost',
            name='scope_of_work',
            field=models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategory',
            name='second_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstCatThird', to='post.secondlevelcategory'),
        ),
    ]
