# Generated by Django 3.2.9 on 2021-12-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_popupquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpp',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='tpp',
            name='refund_policy',
        ),
        migrations.RemoveField(
            model_name='tpp',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='tpp',
            name='shipping_policy',
        ),
    ]
