# Generated by Django 3.2.9 on 2022-01-17 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubmission',
            name='unique_submission',
        ),
        migrations.AlterField(
            model_name='competion',
            name='admin_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
